config/routes.rb
ClientManager::Engine.routes.draw do
  root to: 'sessions#login'
  get 'login', to: 'sessions#login'
  get 'logout', to: 'sessions#logout'
  post 'login_attempt', to: 'sessions#login_attempt'
  get 'change_password', to: 'passwords#change'
  post 'change_password_attempt', to: 'passwords#change_password_attempt'
  resources :clients
  resources :users
end

app/models/client_manager/application_record.rb
module ClientManager
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/client_manager/client.rb
module ClientManager
  class Client < ApplicationRecord
    belongs_to :user
    after_create :generate_token, unless: :token_exists?
    validates_presence_of :name, :user_id
    validate :number_of_users_clients


    def token_exists?
      !self.token.blank?
    end


    private

    def generate_token
      if ClientManager.token_secret.blank?
        raise "config.token_secret is missing. Please set it in the client_manager.rb initializer."
      end
      payload = {client_id: id}
      puts payload
      token = JWT.encode payload, ClientManager.token_secret, 'HS256'
      self.update(token: token)
    end

    def number_of_users_clients
      if !self.user.superadmin && self.user.maximum_number_of_clients <= self.user.clients.count
ut      end
    end

  end
end

app/models/client_manager/user.rb
require 'securerandom'

module ClientManager
  class User < ApplicationRecord
    has_secure_password

    default_scope { order('created_at DESC') }
    validates :name, :email, presence: true
    validates :email, presence: true, uniqueness: true
    validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates_numericality_of :maximum_number_of_clients, allow_nil: true

    before_validation :set_temporary_password, unless: :password_exists?
    after_create :send_registration_email
    has_many :clients, dependent: :destroy

    def client_count
      clients.count
    end

    def self.create_superadmin(name, email, password)
      ClientManager::User.create(name: name, email: email, password: password, superadmin: true, maximum_number_of_clients: nil, password_changed: true)
    end

    private

    def password_exists?
      !self.password_digest.blank?
    end

    def set_temporary_password
      self.password = SecureRandom.hex(6)
    end

    def send_registration_email
      if !self.superadmin
        RegistrationMailer.registration_email(self).deliver
      end
    end

  end
end

app/controllers/client_manager/application_controller.rb
module ClientManager
  class ApplicationController < ActionController::Base
    use_growlyflash
    protect_from_forgery with: :exception

    def client_manager_current_user
      @client_manager_current_user ||= session[:client_manager_current_user_id] && ClientManager::User.find_by_id(session[:client_manager_current_user_id])
    end


    def authenticate_user
      if !client_manager_current_user
        flash[:error] = "Unauthorized"
        redirect_to login_path
      elsif !client_manager_current_user.password_changed
        flash[:error] = "You must change your password before proceeding"
        redirect_to change_password_path
      end
    end

    def authenticate_superadmin
      authenticate_user
      if !client_manager_current_user.superadmin
        flash[:error] = "Unauthorized"
        redirect_to login_path
      end
    end

    helper_method :client_manager_current_user
  end
end

app/controllers/client_manager/clients_controller.rb
module ClientManager
  class ClientsController < ApplicationController
    before_action :authenticate_user
    before_action :set_client, only: [:edit, :show, :update, :destroy]
    layout "client_manager/none", only: [:new, :show]

    def index
      @clients = ClientManager::Client.where(user_id: client_manager_current_user.id)
    end

    def new
      @client = client_manager_current_user.clients.new
    end

    def show

    end

    def create
      @client = client_manager_current_user.clients.new(client_params)
      if @client.save
        flash[:success] = "Client successfully created"
      else
        flash[:error] = @client.errors.empty? ? "Error" : @client.errors.full_messages.uniq.to_sentence
      end
      redirect_to clients_path
    end

    def destroy
      @client.destroy
      redirect_to clients_path
    end


    private


    def set_client
      @client = ClientManager::Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name)
    end
  end
end

app/controllers/client_manager/concerns/set_client_by_token.rb
module ClientManager::Concerns::SetClientByToken
  extend ActiveSupport::Concern

  included do
    before_action :set_client
    if respond_to?(:helper_method)
      helper_method :current_client
    end
  end


  def unauthorized
    head 401
  end

  private

  def set_client
    client_token = request.headers["HTTP_CLIENT_TOKEN"] || params["client-token"]
    if !(client_token.blank?)
      begin
        decoded = JWT.decode client_token, ClientManager.token_secret, true, {:algorithm => 'HS256'}
      rescue JWT::DecodeError
        return unauthorized
      end
      if ClientManager::Client.exists?(decoded[0]["client_id"])
        @current_client = ClientManager::Client.find(decoded[0]["client_id"])
      else
        return unauthorized
      end
    else
      return unauthorized
    end
  end


  def current_client
    @current_client
  end

end

app/controllers/client_manager/passwords_controller.rb
require_dependency "client_manager/application_controller"

module ClientManager
  class PasswordsController < ApplicationController

    def change

    end

    def change_password_attempt
      if params[:new_password] == params[:confirm_new_password]
        client_manager_current_user.update(password: params[:new_password], password_changed: true)
        flash[:notice] = "Successfully changed password"
        redirect_to login_path
      else
        flash[:error] = "Passwords do not match"
        render 'change'
      end
    end


    def password_change_params
      params.permit(:new_password, :confirm_new_password)
    end
  end
end

app/controllers/client_manager/sessions_controller.rb
require_dependency "client_manager/application_controller"

module ClientManager
  class SessionsController < ApplicationController

    def login
      redirect_to after_login_path if client_manager_current_user
    end

    def logout
      session.delete(:client_manager_current_user_id)
      redirect_to login_path
    end

    def login_attempt
      authorized_user = ClientManager::User.find_by(email: params[:email]).try(:authenticate, params[:password])

      if !authorized_user
        flash[:error] = "Invalid Email or Password"
        redirect_to login_path
      else
        session[:client_manager_current_user_id] = authorized_user.id
        redirect_to after_login_path
      end

    end


    def after_login_path
      if client_manager_current_user.superadmin
        return users_path
      else
        return clients_path
      end
    end

  end
end

app/controllers/client_manager/users_controller.rb
require_dependency "client_manager/application_controller"


module ClientManager
  class UsersController < ApplicationController
    before_action :set_user, only: [:destroy, :update, :edit]
    before_action :authenticate_superadmin, except: [:edit, :update]
    before_action :authenticate_editor, only: [:edit, :update]
    before_action :set_edit_view_variables, only: [:edit]
    layout "client_manager/none", only: [:new, :edit]

    def new
      @user = ClientManager::User.new
    end

    def index
      @users = ClientManager::User.where.not(id: client_manager_current_user.id, superadmin: true)
    end

    def edit
      session[:return_to] ||= request.referer
    end

    def update
      @user.assign_attributes(user_update_params)
      return if password_change_attempted? && !handle_password_update
      return if max_clients_is_too_low?
      if @user.save
        flash[:success] = "User successfully updated"
      else
        flash[:error] = @user.errors.empty? ? "Error" : @user.errors.full_messages.uniq.to_sentence
      end

      redirect_to session.delete(:return_to)
    end

    def create
      @user = ClientManager::User.new(user_params)
      if @user.save
        flash[:success] = "User successfully created"
      else
        flash[:error] = @user.errors.empty? ? "Error" : @user.errors.full_messages.uniq.to_sentence
      end
      redirect_to users_path
    end


    def destroy
      @user.destroy
      flash[:success] = "User successfully deleted"
      redirect_to users_path
    end


    private


    def authenticate_editor
      if !(client_manager_current_user == @user)
        authenticate_superadmin
      end
    end

    def set_edit_view_variables
      @modal_title = "MY PROFILE" if client_manager_current_user == @user
      @client_manager_current_user_is_superadmin = @user.superadmin && @user == client_manager_current_user

      if @client_manager_current_user_is_superadmin
        @max_clients = "Infinity"
        @input_type = "text"
      else
        @max_clients = @user.maximum_number_of_clients
        @input_type = "number"
      end

      if client_manager_current_user == @user
        @button_text = "Save Profile"
      else
        @button_text = "Save User"
      end
    end

    def max_clients_is_too_low?
      if !(params[:user][:maximum_number_of_clients].blank?) && (params[:user][:maximum_number_of_clients].to_i <= @user.clients.count)
        flash[:error] = "User already has #{@user.clients.count} clients. Max. number of clients cannot be lower."
        redirect_to session.delete(:return_to)
        return true
      end
      return false
    end

    def handle_password_update
      if @new_password != @new_password_confirmation
        flash[:error] = "Confirmation password mismatch. Password not changed. Nothing was updated."
        redirect_to session.delete(:return_to)
        return false
      else
        @user.assign_attributes(password: @new_password)
        flash[:success] = "Password changed successfully"
        return true
      end
    end

    def password_change_attempted?
      @new_password = params[:user][:new_password]; @new_password_confirmation = params[:user][:new_password_confirmation]
      return (!@new_password.blank? || !@new_password_confirmation.blank?) && client_manager_current_user == @user
    end

    def set_user
      @user = ClientManager::User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :maximum_number_of_clients)
    end

    def user_update_params
      params.require(:user).permit(:name, :maximum_number_of_clients)
    end
  end
end

app/helpers/client_manager/application_helper.rb
module ClientManager
  module ApplicationHelper

  end
end

app/helpers/client_manager/passwords_helper.rb
module ClientManager
  module PasswordsHelper
  end
end

app/helpers/client_manager/sessions_helper.rb
module ClientManager
  module SessionsHelper
  end
end

app/helpers/client_manager/users_helper.rb
module ClientManager
  module UsersHelper
  end
end

app/views/client_manager/clients/index.html.erb
<%= render 'layouts/client_manager/partials/header', path: new_client_path, path_title: 'Add New Client' %>
<main id="main-container">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          Clients
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="content-grid push-50">
      <div class="row">

        <% @clients.each do |client| %>
            <div class="col-lg-4">
              <div class="block block-link-hover3">
                <div class="block-content block-content-full clearfix">
                  <a href="<%= client_path(client) %>" data-method="delete" data-confirm="Are you sure you want to delete this client?" class="icon-btn">
                    <span class="sr-only">Delete Client <%= client.name %></span>
                    <i class="fa fa-trash fa-2x text-danger text-muted" aria-hidden="true"></i>
                  </a>
                  <a class="icon-btn" data-toggle="modal" data-target="#modal" href="<%= client_path(client) %>">
                    <span class="sr-only">View Details for Client <%= client.name %></span>
                    <i class="fa fa-eye fa-2x text-primary text-muted" aria-hidden="true"></i>
                  </a>
                  <h2 class="h4 font-w700"><%= client.name %></h2>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</main>
</div>

app/views/client_manager/clients/new.html.erb
<%= form_for @client, html: {class: "form-horizontal push-5-t"} do |user_form| %>
    <div class="block block-themed block-transparent remove-margin-b">
      <div class="block-header bg-primary-dark">
        <ul class="block-options">
          <li>
            <button data-dismiss="modal" type="button">
              <span class="sr-only">Close Modal</span>
              <i class="fa fa-close" aria-hidden="true"></i>
            </button>
          </li>
        </ul>
        <h3 class="block-title">New Client</h3>
      </div>
      <div class="block-content">
        <div class="form-group">
          <%= user_form.label :name, class: "col-xs-12", required: true %>
          <div class="col-xs-12">
            <%= user_form.text_field :name, class: "form-control", required: true, placeholder: "Example - 'Android Staging', 'Angular Prod'" %>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-sm btn-success" type="submit"><i class="fa fa-check" aria-hidden="true"></i> Save client</button>
          <button class="btn btn-sm btn-danger" type="button" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
<% end %>

app/views/client_manager/clients/show.html.erb
<div class="form-horizontal push-5-t">
  <div class="block block-themed block-transparent remove-margin-b">
    <div class="block-header bg-primary-dark">
      <ul class="block-options">
        <li>
          <button data-dismiss="modal" type="button">
            <span class="sr-only">Close Modal</span>
            <i class="fa fa-close" aria-hidden="true"></i>
          </button>
        </li>
      </ul>
      <h3 class="block-title"><%= @client.name %></h3>
    </div>
    <div class="block-content">
      <div class="form-group">
        <label class="col-xs-12">Token</label>
        <div class="col-xs-12">
          <input class="form-control" id="token" type="text" value="<%= @client.token %>" disabled="true">
        </div>
      </div>
      <div class="modal-footer">
        <a id="copy" class="btn btn-sm btn-default" type="button" data-clipboard-text="<%= @client.token %>">
          <span class="sr-only">Copy Token</span>
          <i class="fa fa-clipboard" aria-hidden="true"></i>
        </a>
        <a class="btn btn-sm btn-danger" type="button" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    var clipboard = new Clipboard('#copy');

    clipboard.on('success', function (e) {
      var token = document.getElementById('token')
      token.setSelectionRange(0, token.value.length)
    });
  })
</script>